### PR TITLE
Make password generation configurable.

### PR DESCRIPTION
**Pull request by zongzw**

### CODE REVIEW

**Comment by zongzw** [comment]
Test result: 
```
            "connection": {
                "username": "admin",
                "password": "k3jApA?/|n4A",
                "rootPass": "-FOc^OT2QFO?",
                "tcpPort": 443,
                "ipAddress": "10.250.15.158"
            },
```

**Comment by zongzw** [comment]
@olvandeng, will we re-define the acceptance criteria again. 
@zhaoqin-github We are reaching to the end of the sprint. Why not you post your suggestion earlier?

**Comment by zongzw** [comment]
> seems to me this does not work. did you test the setup process,etc? need to take care of some hardcoded passwords so that it does not break anything.

Of course, I tested it and it works well. Just now I tested it again, the processes till to installing as3 are OK.   (partition creation fails, but it seems no matter with password, because we have created the trust. )

What's the issue posted from it?

**Comment by Niklaus-xie** [comment]
> > seems to me this does not work. did you test the setup process,etc? need to take care of some hardcoded passwords so that it does not break anything.
> 
> Of course, I tested it and it works well. Just now I tested it again, the processes till to installing as3 are OK. (partition creation fails, but it seems no matter with password, because we have created the trust. )
> 
> What's the issue posted from it?

that is exactly the problem. it can create the partition correctly before this patch,  but it can not do that now with this patch.  so you should find out why the password generation causes that issue, otherwise, this patch can not be merged because it introduces issues(the setup api does not succeed).  As i mentioned, it is probably because of some hardcoded passwords earlier.

**Comment by zongzw** [comment]
> > > seems to me this does not work. did you test the setup process,etc? need to take care of some hardcoded passwords so that it does not break anything.
> > 
> > 
> > Of course, I tested it and it works well. Just now I tested it again, the processes till to installing as3 are OK. (partition creation fails, but it seems no matter with password, because we have created the trust. )
> > What's the issue posted from it?
> 
> that is exactly the problem. it can create the partition correctly before this patch, but it can not do that now with this patch. so you should find out why the password generation causes that issue, otherwise, this patch can not be merged because it introduces issues(the setup api does not succeed). As i mentioned, it is probably because of some hardcoded passwords earlier.

Thanks for finding this. It's indeed the problem. 
@jikui help fixed in PR https://github.com/F5Networks/f5-adcaas-openstack/pull/265. After rebasing the code, tested again. works ok for now.

**Comment by Niklaus-xie** [comment]
> > > > seems to me this does not work. did you test the setup process,etc? need to take care of some hardcoded passwords so that it does not break anything.
> > > 
> > > 
> > > Of course, I tested it and it works well. Just now I tested it again, the processes till to installing as3 are OK. (partition creation fails, but it seems no matter with password, because we have created the trust. )
> > > What's the issue posted from it?
> > 
> > 
> > that is exactly the problem. it can create the partition correctly before this patch, but it can not do that now with this patch. so you should find out why the password generation causes that issue, otherwise, this patch can not be merged because it introduces issues(the setup api does not succeed). As i mentioned, it is probably because of some hardcoded passwords earlier.
> 
> Thanks for finding this. It's indeed the problem.
> @jikui help fixed in PR #265. After rebasing the code, tested again. works ok for now.
cool.

**Pull request merged**
